import MoviesDrawer from "@/app/components/Drawer/MoviesDrawer";

export const metadata = {
  title: "aTe MDB",
  description: "Generated by create next app",
};

export default function MoviesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MoviesDrawer />
        {children}
      </body>
    </html>
  );
}
