import TemporaryDrawer from "@/components/Drawer/TemporaryDrawer";
import "./globals.css";
import SupabaseProvider from "./supabase-provider";

export const metadata = {
  title: "aTe MDB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TemporaryDrawer />
        {/* <SupabaseProvider> */}
        {children}
        {/* </SupabaseProvider> */}
      </body>
    </html>
  );
}
