import "./globals.css";
import {SupabaseProvider} from "./components/Supabase/supabase-provider";
import AuthProvider from "@/app/components/Supabase/auth-provider";
import ToasterProvider from "@/app/components/Toast/ToasterProvider";

export const metadata = {
  title: "aTe MDB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" sizes="32x32" />
      <body>
        <SupabaseProvider>
          <AuthProvider>
            <ToasterProvider />
            {children}
          </AuthProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
