import TemporaryDrawer from "@/app/components/Drawer/TemporaryDrawer";

export const metadata = {
  title: "aTe MDB",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TemporaryDrawer />
        {children}
      </body>
    </html>
  );
}
